"use client"
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { TypeAnimation } from 'react-type-animation';
import HeroSection from "@/components/Home/HeroSection";
import TopNavigation from "@/components/TopNavigation/Navigation";
import AboutMe from "@/components/Home/AboutMe";
import Services from "@/components/Home/Services";
import Experience from "@/components/Home/Experience";
import Portfolio from "@/components/Home/Portfolio";
import ContactUs from "@/components/Home/ContactUs";
import Blogs from "@/components/Home/Blogs";
import Layout from "@/components/Layout/Layout";
import { useEffect } from "react";
const inter = Inter({ subsets: ["latin"] });


export default function Home() {

useEffect(()=>{
  // Portfolio filter
  var portfolioIsotope = $('.portfolio-container').isotope({
    itemSelector: '.portfolio-item',
    layoutMode: 'fitRows'
});

$('#portfolio-filter li').on('click', function () {
    $("#portfolio-filter li").removeClass('filter-active');
    $(this).addClass('filter-active');
    portfolioIsotope.isotope({filter: $(this).data('filter')});
});
})

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />
<link href="lib/animate/animate.min.css" rel="stylesheet" />
<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
<link href="lib/lightbox/css/lightbox.min.css" rel="stylesheet" />
      </Head>
      <Layout>
        
          <HeroSection />
        <AboutMe />
         <Services />
         <Experience />
          <Portfolio />
        
   
         <ContactUs />
           <Blogs />
        
           </Layout>   
           
    </>
    
  );
}
